// Generated by CoffeeScript 1.3.1
(function() {
  var Anvil, FP, Scheduler, log, scheduler, _;

  _ = require("underscore");

  log = require("./logMock.coffee").log;

  FP = require("./fsMock.coffee").fsProvider;

  Anvil = require("../src/anvil");

  Scheduler = require("../src/scheduler.coffee").scheduler;

  scheduler = new Scheduler();

  require("should");

}).call(this);
