// Generated by CoffeeScript 1.3.1
(function() {
  var Crawler, FSProvider, Scheduler, crawler, fp, log, path, scheduler, _;

  _ = require("underscore");

  log = require("./logMock.coffee").log;

  path = require("path");

  Scheduler = require("../src/scheduler.coffee").scheduler;

  scheduler = new Scheduler();

  Crawler = require("../src/crawler.coffee").crawler;

  crawler = new Crawler(scheduler);

  FSProvider = require("../src/file").fsProvider;

  fp = new FSProvider(crawler, log);

  require("should");

  describe("when listing files from a directory structure", function() {
    return it("should get complete file list", function(done) {
      return fp.getFiles("../ext", function(files) {
        files.length.should.equal(5);
        return done();
      });
    });
  });

}).call(this);
